import 'package:hive/hive.dart';
import 'package:untitled/local_storage/video_game.dart';
import 'package:untitled/twitch/twitch_api.dart';
import 'package:uuid/v4.dart';

part 'generic_video_game_model.g.dart';

@HiveType(typeId: 4)
class VideoGameModel {
  @HiveField(1)
  final String title;
  @HiveField(2)
  final String? description;
  @HiveField(3)
  /// specific like nintendo switch, xbox 360, sega game gear
  final GamingPlatform platform;
  @HiveField(4)
  final String? ean; // bar code number as string
  @HiveField(5)
  final String? imageUrl;
  @HiveField(6)
  final String? imageBase64;
  @HiveField(7)
  final String? uuid;
  @HiveField(8)
  final GamingPlatformEnum gamingPlatformEnum;
  @HiveField(9)
  final int numberOfCopiesOwned;

  VideoGameModel(

      {
        required this.gamingPlatformEnum,
      required this.uuid,
      required this.numberOfCopiesOwned,
      required this.title,
      required this.description,
      required this.platform,
      required this.ean,
      required this.imageUrl,
      required this.imageBase64});

  static VideoGameModel fromItems(Items item) {
    return VideoGameModel(
        title: item.title ?? "",
        numberOfCopiesOwned: 1,
        description: item.description,
        platform: _getGaminPlatformFromItem(),
        gamingPlatformEnum: _getGamingPlatformEnum(item.brand),
        ean: item.ean,
        uuid: const UuidV4().generate(),
        imageUrl: item.images?.firstOrNull ?? "",
        imageBase64: null);
  }

  static GamingPlatform _getGaminPlatformFromItem() {
    return GamingPlatform(twitchiId: "", name: 'no name');
  }

  VideoGameModel copyWithBase64Image({
    String? title,
    String? description,
    GamingPlatform? platform,
    String? ean,
    String? imageUrl,
    required String imageBase64,
  }) {
    return VideoGameModel(
      title: this.title,
      description: this.description,
      platform: this.platform,
      ean: this.ean,
      imageUrl: null,
      uuid: uuid,
      imageBase64: imageBase64,
      gamingPlatformEnum: gamingPlatformEnum, numberOfCopiesOwned: numberOfCopiesOwned,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'title': title,
      'description': description,
      'platform': platform.name,
      'ean': ean,
      'imageUrl': imageUrl,
      'imageBase64': imageBase64,
      "gamingPlatformEnum": gamingPlatformEnum.name,
      'uuid': uuid,
      'numberOfCopiesOwned': numberOfCopiesOwned
    };
  }
  @Deprecated("not used anywhere, autogenerated though")
  factory VideoGameModel.fromMap(Map<String, dynamic> map) {
    return VideoGameModel(
      title: map['title'] as String,
      description: map['description'] as String,
      platform: map['platform'] as GamingPlatform,
      ean: map['ean'] as String,
      imageUrl: map['imageUrl'] as String,
      imageBase64: map['imageBase64'] as String,
      uuid: map['uuid'] as String,
      gamingPlatformEnum: GamingPlatformEnum.values
          .firstWhere((e) => e.name == map["gamingPlatformEnum"]), numberOfCopiesOwned: 1,
    );
  }

  static GamingPlatformEnum _getGamingPlatformEnum(String? brand) {
    try {
      return GamingPlatformEnum.values.firstWhere(
          (GamingPlatformEnum platformEnum) =>
              platformEnum.name == brand?.toLowerCase());
    } catch (e, _) {
      print("Could not assign a proper platorm to $brand");
      return GamingPlatformEnum.unknown;
    }
  }

  VideoGameModel withAdditionalCopy() {
    return _copyWith(numberOfCopiesOwned: numberOfCopiesOwned + 1);
  }

  VideoGameModel _copyWith({
    String? title,
    String? description,
    GamingPlatform? platform,
    String? ean,
    String? imageUrl,
    String? imageBase64,
    String? uuid,
    GamingPlatformEnum? gamingPlatformEnum,
    int? numberOfCopiesOwned,
  }) {
    return VideoGameModel(
      title: title ?? this.title,
      description: description ?? this.description,
      platform: platform ?? this.platform,
      ean: ean ?? this.ean,
      imageUrl: imageUrl ?? this.imageUrl,
      imageBase64: imageBase64 ?? this.imageBase64,
      uuid: uuid ?? this.uuid,
      gamingPlatformEnum: gamingPlatformEnum ?? this.gamingPlatformEnum,
      numberOfCopiesOwned: numberOfCopiesOwned ?? this.numberOfCopiesOwned,
    );
  }

}

@HiveType(typeId: 5)
class GamingPlatform {
  @HiveField(1)
  final String twitchiId;
  @HiveField(2)
  final String name;

  GamingPlatform({required this.twitchiId, required this.name});

  Map<String, dynamic> toJson() {
    return {
      'twitchiId': twitchiId,
      'name': name,
    };
  }

  factory GamingPlatform.fromJson(Map<String, dynamic> map) {
    return GamingPlatform(
      twitchiId: map['twitchiId'] as String,
      name: map['name'] as String,
    );
  }
}
